Repository nextimecode/f02-web-academia, pull requests merged in 2021-03, with the labels that each got.

#16 Release/0.6.0
  package.json
  public/assets/img/carouselPhotos/img01.jpg
  public/assets/img/carouselPhotos/img02.jpg
  public/assets/img/carouselPhotos/img03.jpg
  src/components/atoms/separator/index.tsx
  src/components/atoms/subtitle/index.tsx
  src/components/atoms/title/index.tsx
  src/components/organisms/slider/index.tsx
  src/components/templates/home/index.tsx
  src/components/templates/resultados/index.tsx
  src/pages/index.tsx
  src/styles/custom/style.scss
  yarn.lock
Labels: feature

#17 Release/0.7.0
  package.json
  public/assets/video/video_test.mp4
  src/components/atoms/film/index.tsx
  src/components/atoms/separator/index.tsx
  src/components/organisms/slider/index.tsx
  src/components/templates/depoimentosVideo/index.tsx
  src/components/templates/resultados/index.tsx
  src/pages/index.tsx
  src/styles/custom/style.scss
  src/styles/custom/variables.scss
Labels: feature

#18 Release/0.8.0
  package-lock.json
  package.json
  public/assets/img/consultoria.jpg
  src/components/organisms/cardPlanos/index.tsx
  src/components/organisms/cardTreino/index.tsx
  src/components/organisms/perguntasFrequentes/index.tsx
  src/components/templates/beneficiosConsultoria/index.tsx
  src/components/templates/consultoriaPersonalizada/index.tsx
  src/components/templates/entendaConsultoria/index.tsx
  src/components/templates/faq/index.tsx
  src/components/templates/pageTemplate/index.tsx
  src/components/templates/planoTreino/index.tsx
  src/components/templates/planos/index.tsx
  src/components/templates/relacaoConsultoria/index.tsx
  src/components/templates/transformacoesConsultoria/index.tsx
  src/components/templates/videoConsultoria/index.tsx
  src/pages/consultoria.tsx
  src/pages/index.tsx
  yarn.lock
Labels: feature

#19 Release/0.9.0
  package.json
  public/assets/img/avatars/personal.jpg
  public/assets/img/avatars/user.png
  src/components/atoms/textoDepoimento/index.tsx
  src/components/atoms/textoDepoimento/style.scss
  src/components/molecules/avatar/index.tsx
  src/components/molecules/avatar/style.scss
  src/components/molecules/depoimento/index.tsx
  src/components/organisms/depoimentoSlider/index.tsx
  src/components/organisms/menu/index.tsx
  src/components/organisms/photoSlider/index.tsx
  src/components/organisms/slider/index.tsx
  src/components/templates/depoimentosTexto/index.tsx
  src/components/templates/footer/index.tsx
  src/components/templates/header/index.tsx
  src/components/templates/pageTemplate/index.tsx
  src/components/templates/resultados/index.tsx
  src/components/templates/transformacoesConsultoria/index.tsx
  src/pages/index.tsx
  src/styles/custom/style.scss
Labels: feature

#22 Release/0.10.0
  package.json
  prettier.config.js
  src/components/atoms/button/index.tsx
  src/components/atoms/button/styles.scss
  src/components/atoms/subtitle/index.tsx
  src/components/atoms/title/index.tsx
  src/components/molecules/cardPlanos/index.tsx
  src/components/molecules/cardTreino/index.tsx
  src/components/molecules/depoimento/index.tsx
  src/components/organisms/bemVindo/index.tsx
  src/components/organisms/beneficiosConsultoria/index.tsx
  src/components/organisms/depoimentoSlider/index.tsx
  src/components/organisms/depoimentosTexto/index.tsx
  src/components/organisms/depoimentosVideo/index.tsx
  src/components/organisms/entendaConsultoria/index.tsx
  src/components/organisms/faq/index.tsx
  src/components/organisms/footer/index.tsx
  src/components/organisms/header/index.tsx
  src/components/organisms/header/logo.png
  src/components/organisms/hero/index.tsx
  src/components/organisms/home/index.tsx
  src/components/organisms/menu/index.tsx
  src/components/organisms/photoSlider/index.tsx
  src/components/organisms/planoTreino/index.tsx
  src/components/organisms/planos/index.tsx
  src/components/organisms/redesSociais/index.tsx
  src/components/organisms/relacaoConsultoria/index.tsx
  src/components/organisms/resultados/index.tsx
  src/components/organisms/transformacoesConsultoria/index.tsx
  src/components/organisms/videoConsultoria/index.tsx
  src/components/templates/consultoriaTemplate/index.tsx
  src/components/templates/homeTemplate/index.tsx
  src/components/templates/pageTemplate/index.tsx
  src/pages/consultoria.tsx
  src/pages/index.tsx
  src/styles/custom/style.scss
  src/types/types.ts
  yarn.lock
Labels: feature

#25 Release/0.11.0
  .eslintrc.json
  package.json
  src/components/atoms/price/index.tsx
  src/components/atoms/priceCurrency/index.tsx
  src/components/atoms/priceFrequency/index.tsx
  src/components/atoms/priceValue/index.tsx
  src/components/atoms/separator/index.tsx
  src/components/molecules/cardPlanos/index.tsx
  src/components/molecules/price/index.tsx
  src/components/organisms/bemVindo/index.tsx
  src/components/organisms/depoimentosTexto/index.tsx
  src/components/organisms/footer/index.tsx
  src/components/organisms/header/index.tsx
  src/components/organisms/perguntasFrequentes/index.tsx
  src/components/organisms/perguntasFrequentes/style.scss
  src/components/organisms/photoSlider/index.tsx
  src/components/organisms/photoSlider/style.scss
  src/components/organisms/planos/index.tsx
  src/components/organisms/redesSociais/index.tsx
  src/components/organisms/resultados/index.tsx
  src/components/templates/homeTemplate/index.tsx
  src/pages/index.tsx
  src/styles/custom/style.scss
  src/types/types.ts
Labels: feature, improvment

#26 Release/0.12.0
  package.json
  public/assets/img/logos/logo.png
  public/assets/img/personal.png
  public/favicon.png
  src/components/atoms/button/index.tsx
  src/components/atoms/button/styles.scss
  src/components/atoms/separator/index.tsx
  src/components/atoms/separator/styles.scss
  src/components/atoms/title/index.tsx
  src/components/atoms/video/index.tsx
  src/components/molecules/cardAcessos/index.tsx
  src/components/molecules/cardPlanos/index.tsx
  src/components/molecules/price/index.tsx
  src/components/organisms/bemVindo/index.tsx
  src/components/organisms/beneficiosConsultoria/index.tsx
  src/components/organisms/conteudoTreino/index.tsx
  src/components/organisms/depoimentosTexto/index.tsx
  src/components/organisms/faq/index.tsx
  src/components/organisms/header/index.tsx
  src/components/organisms/hero/index.tsx
  src/components/organisms/home/index.tsx
  src/components/organisms/menu/index.tsx
  src/components/organisms/perguntasFrequentes/index.tsx
  src/components/organisms/photoSlider/style.scss
  src/components/organisms/planos/index.tsx
  src/components/organisms/relacaoConsultoria/index.tsx
  src/components/organisms/resultados/index.tsx
  src/components/organisms/treinoPreco/index.tsx
  src/components/organisms/treinosFuncionam/index.tsx
  src/components/organisms/videoConsultoria/index.tsx
  src/components/organisms/videoTreino/index.tsx
  src/components/templates/consultoriaTemplate/index.tsx
  src/components/templates/pageTemplate/index.tsx
  src/components/templates/treinoTemplate/index.tsx
  src/pages/consultoria.tsx
  src/pages/index.tsx
  src/pages/treino-homens.tsx
  src/pages/treino-mulheres.tsx
  src/styles/custom/style.scss
  src/styles/custom/variables.scss
  src/styles/global.scss
  src/types/types.ts
Labels: feature

#33 Release/0.13.0
  package.json
  public/assets/img/logos/whatsapp.png
  src/components/atoms/priceFrequency/index.tsx
  src/components/molecules/cardAcessos/index.tsx
  src/components/molecules/cardAcessos/style.scss
  src/components/molecules/cardPlanos/index.tsx
  src/components/molecules/consultoriaCard/index.tsx
  src/components/molecules/consultoriaCard/style.scss
  src/components/molecules/price/index.tsx
  src/components/organisms/consultoriaBeneficios/index.tsx
  src/components/organisms/consultoriaEntenda/index.tsx
  src/components/organisms/consultoriaPagamento/index.tsx
  src/components/organisms/consultoriaPagamento/style.scss
  src/components/organisms/consultoriaRelacao/index.tsx
  src/components/organisms/consultoriaTransformacoes/index.tsx
  src/components/organisms/consultoriaVideo/index.tsx
  src/components/organisms/depoimentosTexto/index.tsx
  src/components/organisms/footer/index.tsx
  src/components/organisms/footer/style.scss
  src/components/organisms/header/index.tsx
  src/components/organisms/home/index.tsx
  src/components/organisms/home/style.scss
  src/components/organisms/menu/index.tsx
  src/components/organisms/menu/style.scss
  src/components/organisms/planos/index.tsx
  src/components/organisms/resultados/index.tsx
  src/components/organisms/treinoConteudo/index.tsx
  src/components/organisms/treinoPreco/index.tsx
  src/components/organisms/treinosFuncionam/index.tsx
  src/components/organisms/videoTreino/index.tsx
  src/components/templates/consultoriaTemplate/index.tsx
  src/components/templates/pageTemplate/index.tsx
  src/components/templates/treinoTemplate/index.tsx
  src/pages/treino-homens.tsx
  src/pages/treino-mulheres.tsx
Labels: bug, feature, improvement
